"""Builds the About, How it works, Privacy and Contact pages in every language from the English ones:
python i18n_pages.py  ->  pages/fr/about.html, pages/es/about.html, ...  (run again after changing an English page or a text below).
Each row: the English text exactly as it is in the page, then fr, es, de, it, pt, ar. Links get the language part (/fr/...)."""
import os, re

LANGS = ["fr", "es", "de", "it", "pt", "ar"]
HERE = os.path.dirname(os.path.abspath(__file__))
SEC = {"fr": "films", "es": "peliculas", "de": "filme", "it": "film", "pt": "filmes", "ar": "movies"}

T = [
# ---- shared ----
["Back to the catalogue", "Retour au catalogue", "Volver al catálogo", "Zurück zum Katalog", "Torna al catalogo", "Voltar ao catálogo", "العودة إلى الكتالوج"],
[">Catalogue<", ">Catalogue<", ">Catálogo<", ">Katalog<", ">Catalogo<", ">Catálogo<", ">الكتالوج<"],
[">News<", ">Actualités<", ">Noticias<", ">News<", ">Notizie<", ">Notícias<", ">الأخبار<"],
[">About<", ">À propos<", ">Acerca de<", ">Über uns<", ">Chi siamo<", ">Sobre<", ">حول<"],
[">How it works<", ">Comment ça marche<", ">Cómo funciona<", ">So funktioniert’s<", ">Come funziona<", ">Como funciona<", ">كيف يعمل<"],
[">Contact<", ">Contact<", ">Contacto<", ">Kontakt<", ">Contatti<", ">Contato<", ">اتصل بنا<"],
[">Privacy<", ">Confidentialité<", ">Privacidad<", ">Datenschutz<", ">Privacy<", ">Privacidade<", ">الخصوصية<"],
[">Home<", ">Accueil<", ">Inicio<", ">Start<", ">Home<", ">Início<", ">الرئيسية<"],
["Information courtesy of IMDb (", "Informations fournies par IMDb (", "Información cortesía de IMDb (", "Informationen mit freundlicher Genehmigung von IMDb (", "Informazioni per gentile concessione di IMDb (", "Informações cedidas pelo IMDb (", "المعلومات بإذن من IMDb ("],
["). Used with permission.", "). Utilisées avec autorisation.", "). Usada con permiso.", "). Mit Genehmigung verwendet.", "). Usate con autorizzazione.", "). Usadas com permissão.", "). مستخدمة بإذن."],

# ---- about ----
["<title>About · Nahoko</title>", "<title>À propos · Nahoko</title>", "<title>Acerca de · Nahoko</title>", "<title>Über uns · Nahoko</title>", "<title>Chi siamo · Nahoko</title>", "<title>Sobre · Nahoko</title>", "<title>حول · Nahoko</title>"],
["Nahoko is a passion project: a calm place to discover films, series and games.", "Nahoko est un projet passion : un endroit calme pour découvrir des films, des séries et des jeux.", "Nahoko es un proyecto personal: un lugar tranquilo para descubrir películas, series y juegos.", "Nahoko ist ein Herzensprojekt: ein ruhiger Ort, um Filme, Serien und Spiele zu entdecken.", "Nahoko è un progetto per passione: un posto tranquillo per scoprire film, serie e giochi.", "Nahoko é um projeto feito por paixão: um lugar calmo para descobrir filmes, séries e jogos.", "Nahoko مشروع شغف: مكان هادئ لاكتشاف الأفلام والمسلسلات والألعاب."],
["<h1>About Nahoko</h1>", "<h1>À propos de Nahoko</h1>", "<h1>Acerca de Nahoko</h1>", "<h1>Über Nahoko</h1>", "<h1>Chi è Nahoko</h1>", "<h1>Sobre o Nahoko</h1>", "<h1>حول Nahoko</h1>"],
["A passion project: a calm, fast place to discover films, series, anime and games, without ads and without noise.", "Un projet passion : un endroit calme et rapide pour découvrir films, séries, anime et jeux, sans publicité et sans bruit.", "Un proyecto personal: un lugar tranquilo y rápido para descubrir películas, series, anime y juegos, sin anuncios ni ruido.", "Ein Herzensprojekt: ein ruhiger, schneller Ort für Filme, Serien, Anime und Spiele, ohne Werbung und ohne Lärm.", "Un progetto per passione: un posto tranquillo e veloce per scoprire film, serie, anime e giochi, senza pubblicità e senza rumore.", "Um projeto feito por paixão: um lugar calmo e rápido para descobrir filmes, séries, anime e jogos, sem anúncios e sem barulho.", "مشروع شغف: مكان هادئ وسريع لاكتشاف الأفلام والمسلسلات والأنمي والألعاب، بلا إعلانات ولا ضجيج."],
["Made by one developer, for friends and family.", "Fait par un seul développeur, pour les amis et la famille.", "Hecho por un solo desarrollador, para amigos y familia.", "Von einem einzigen Entwickler gemacht, für Freunde und Familie.", "Fatto da un solo sviluppatore, per amici e famiglia.", "Feito por um único desenvolvedor, para amigos e família.", "صنعه مطوّر واحد، للأصدقاء والعائلة."],
["Nahoko is built and run on a small personal server. No company, no investors, nothing to sell.", "Nahoko est construit et hébergé sur un petit serveur personnel. Pas d’entreprise, pas d’investisseurs, rien à vendre.", "Nahoko se construye y funciona en un pequeño servidor personal. Sin empresa, sin inversores, nada que vender.", "Nahoko läuft auf einem kleinen privaten Server. Keine Firma, keine Investoren, nichts zu verkaufen.", "Nahoko è costruito e gira su un piccolo server personale. Nessuna azienda, nessun investitore, niente da vendere.", "O Nahoko é feito e roda num pequeno servidor pessoal. Sem empresa, sem investidores, nada para vender.", "يعمل Nahoko على خادم شخصي صغير. لا شركة ولا مستثمرون ولا شيء للبيع."],
["How it works and where the information comes from", "Comment ça marche et d’où viennent les informations", "Cómo funciona y de dónde viene la información", "So funktioniert’s und woher die Informationen kommen", "Come funziona e da dove vengono le informazioni", "Como funciona e de onde vêm as informações", "كيف يعمل ومن أين تأتي المعلومات"],
["<h2>What you can do</h2>", "<h2>Ce que tu peux faire</h2>", "<h2>Qué puedes hacer</h2>", "<h2>Was du tun kannst</h2>", "<h2>Cosa puoi fare</h2>", "<h2>O que você pode fazer</h2>", "<h2>ما يمكنك فعله</h2>"],
["Browse more than 30,000 films and series, with ratings, cast, trailers and every episode of every season.", "Parcourir plus de 30 000 films et séries, avec les notes, la distribution, les bandes-annonces et chaque épisode de chaque saison.", "Explorar más de 30.000 películas y series, con notas, reparto, tráileres y cada episodio de cada temporada.", "Mehr als 30.000 Filme und Serien durchstöbern, mit Bewertungen, Besetzung, Trailern und jeder Folge jeder Staffel.", "Sfogliare più di 30.000 film e serie, con voti, cast, trailer e ogni episodio di ogni stagione.", "Explorar mais de 30.000 filmes e séries, com notas, elenco, trailers e cada episódio de cada temporada.", "تصفح أكثر من 30,000 فيلم ومسلسل، مع التقييمات وطاقم التمثيل والإعلانات وكل حلقة من كل موسم."],
["Save your favorites and find them on every device (sign in with your email, no password needed).", "Garder tes favoris et les retrouver sur tous tes appareils (connexion avec ton e-mail, sans mot de passe).", "Guardar tus favoritos y tenerlos en todos tus dispositivos (inicia sesión con tu correo, sin contraseña).", "Deine Favoriten speichern und auf allen Geräten finden (Anmeldung mit E-Mail, ohne Passwort).", "Salvare i preferiti e ritrovarli su ogni dispositivo (accedi con la tua email, senza password).", "Guardar seus favoritos e encontrá-los em todos os aparelhos (entre com seu e-mail, sem senha).", "احفظ مفضلتك وجدها على كل أجهزتك (سجّل الدخول ببريدك، بلا كلمة مرور)."],
["Tell the owner what you would like to watch, and see what others asked for.", "Dire au propriétaire ce que tu aimerais regarder, et voir ce que les autres ont demandé.", "Decirle al dueño qué te gustaría ver y ver lo que pidieron los demás.", "Dem Betreiber sagen, was du sehen möchtest, und sehen, was andere sich wünschen.", "Dire al proprietario cosa vorresti vedere e vedere cosa hanno chiesto gli altri.", "Dizer ao dono o que você gostaria de assistir e ver o que os outros pediram.", "أخبر المالك بما تودّ مشاهدته، وشاهد ما طلبه الآخرون."],
["Can’t choose? Press the dice for a good pick.", "Tu hésites ? Appuie sur le dé pour un bon choix.", "¿No sabes qué ver? Pulsa el dado para una buena elección.", "Unentschlossen? Drück auf den Würfel für einen guten Tipp.", "Indeciso? Premi il dado per una buona scelta.", "Indeciso? Aperte o dado para uma boa escolha.", "محتار؟ اضغط على النرد لاختيار جيد."],
["<h2>Where the information comes from</h2>", "<h2>D’où viennent les informations</h2>", "<h2>De dónde viene la información</h2>", "<h2>Woher die Informationen kommen</h2>", "<h2>Da dove vengono le informazioni</h2>", "<h2>De onde vêm as informações</h2>", "<h2>من أين تأتي المعلومات</h2>"],
["Ratings and titles come from the IMDb datasets. Posters, pictures and descriptions from TMDB, TVmaze and AniList; games from Wikidata and Wikipedia. This product uses the TMDB API but is not endorsed or certified by TMDB. All names, posters and trademarks belong to their owners.", "Les notes et les titres viennent des jeux de données IMDb. Affiches, images et descriptions de TMDB, TVmaze et AniList ; les jeux de Wikidata et Wikipédia. Ce produit utilise l’API TMDB mais n’est ni approuvé ni certifié par TMDB. Les noms, affiches et marques appartiennent à leurs propriétaires.", "Las notas y los títulos vienen de los datos de IMDb. Pósteres, imágenes y descripciones de TMDB, TVmaze y AniList; los juegos de Wikidata y Wikipedia. Este producto usa la API de TMDB pero no está avalado ni certificado por TMDB. Los nombres, pósteres y marcas pertenecen a sus dueños.", "Bewertungen und Titel stammen aus den IMDb-Datensätzen. Poster, Bilder und Beschreibungen von TMDB, TVmaze und AniList; Spiele von Wikidata und Wikipedia. Dieses Produkt nutzt die TMDB-API, ist aber nicht von TMDB unterstützt oder zertifiziert. Namen, Poster und Marken gehören ihren Inhabern.", "Voti e titoli vengono dai dataset di IMDb. Locandine, immagini e descrizioni da TMDB, TVmaze e AniList; i giochi da Wikidata e Wikipedia. Questo prodotto usa l’API di TMDB ma non è approvato né certificato da TMDB. Nomi, locandine e marchi appartengono ai rispettivi proprietari.", "Notas e títulos vêm dos dados do IMDb. Pôsteres, imagens e descrições do TMDB, TVmaze e AniList; jogos da Wikidata e Wikipédia. Este produto usa a API do TMDB, mas não é endossado nem certificado pelo TMDB. Nomes, pôsteres e marcas pertencem aos seus donos.", "التقييمات والعناوين من بيانات IMDb. الملصقات والصور والأوصاف من TMDB وTVmaze وAniList؛ والألعاب من ويكي بيانات وويكيبيديا. يستخدم هذا المنتج واجهة TMDB لكنه غير معتمد منها. كل الأسماء والملصقات والعلامات ملك لأصحابها."],
["<h2>Install it</h2>", "<h2>L’installer</h2>", "<h2>Instálalo</h2>", "<h2>Installieren</h2>", "<h2>Installalo</h2>", "<h2>Instale</h2>", "<h2>ثبّته</h2>"],
["On a phone, open the browser menu and choose <b>Add to Home screen</b> (Android) or <b>Share → Add to Home Screen</b> (iPhone). It opens like an app.", "Sur téléphone, ouvre le menu du navigateur et choisis <b>Ajouter à l’écran d’accueil</b> (Android) ou <b>Partager → Sur l’écran d’accueil</b> (iPhone). Il s’ouvre comme une appli.", "En el móvil, abre el menú del navegador y elige <b>Añadir a pantalla de inicio</b> (Android) o <b>Compartir → Añadir a pantalla de inicio</b> (iPhone). Se abre como una app.", "Öffne auf dem Handy das Browsermenü und wähle <b>Zum Startbildschirm hinzufügen</b> (Android) oder <b>Teilen → Zum Home-Bildschirm</b> (iPhone). Es öffnet sich wie eine App.", "Sul telefono, apri il menu del browser e scegli <b>Aggiungi a schermata Home</b> (Android) o <b>Condividi → Aggiungi alla schermata Home</b> (iPhone). Si apre come un’app.", "No celular, abra o menu do navegador e escolha <b>Adicionar à tela inicial</b> (Android) ou <b>Compartilhar → Adicionar à Tela de Início</b> (iPhone). Abre como um app.", "على الهاتف، افتح قائمة المتصفح واختر <b>إضافة إلى الشاشة الرئيسية</b> (أندرويد) أو <b>مشاركة ← إضافة إلى الشاشة الرئيسية</b> (آيفون). يفتح كتطبيق."],

# ---- privacy ----
["<title>Privacy · Nahoko</title>", "<title>Confidentialité · Nahoko</title>", "<title>Privacidad · Nahoko</title>", "<title>Datenschutz · Nahoko</title>", "<title>Privacy · Nahoko</title>", "<title>Privacidade · Nahoko</title>", "<title>الخصوصية · Nahoko</title>"],
["<h1>Privacy</h1>", "<h1>Confidentialité</h1>", "<h1>Privacidad</h1>", "<h1>Datenschutz</h1>", "<h1>Privacy</h1>", "<h1>Privacidade</h1>", "<h1>الخصوصية</h1>"],
["Short version: we collect nothing about you.", "En bref : nous ne collectons rien sur toi.", "En resumen: no recogemos nada sobre ti.", "Kurz gesagt: Wir sammeln nichts über dich.", "In breve: non raccogliamo nulla su di te.", "Resumindo: não coletamos nada sobre você.", "باختصار: لا نجمع أي شيء عنك."],
["No tracking. No ads. No analytics.", "Pas de pistage. Pas de pub. Pas de statistiques.", "Sin rastreo. Sin anuncios. Sin analíticas.", "Kein Tracking. Keine Werbung. Keine Statistiken.", "Nessun tracciamento. Nessuna pubblicità. Nessuna statistica.", "Sem rastreamento. Sem anúncios. Sem estatísticas.", "لا تتبّع. لا إعلانات. لا إحصاءات."],
["No third-party scripts, no tracking cookies, no fingerprinting, nothing sold or shared. Browsing the catalogue needs no account and leaves nothing behind.", "Aucun script tiers, aucun cookie de pistage, aucune empreinte, rien de vendu ni partagé. Parcourir le catalogue ne demande aucun compte et ne laisse aucune trace.", "Sin scripts de terceros, sin cookies de rastreo, sin huellas digitales, nada vendido ni compartido. Ver el catálogo no requiere cuenta y no deja rastro.", "Keine Fremd-Skripte, keine Tracking-Cookies, kein Fingerprinting, nichts wird verkauft oder geteilt. Der Katalog braucht kein Konto und hinterlässt keine Spuren.", "Nessuno script di terzi, nessun cookie di tracciamento, nessuna impronta digitale, niente venduto o condiviso. Sfogliare il catalogo non richiede un account e non lascia tracce.", "Sem scripts de terceiros, sem cookies de rastreamento, sem impressão digital, nada vendido ou compartilhado. Navegar no catálogo não exige conta e não deixa rastros.", "لا نصوص من أطراف ثالثة، ولا ملفات تعريف للتتبع، ولا بصمة رقمية، ولا شيء يُباع أو يُشارك. تصفح الكتالوج لا يحتاج حسابًا ولا يترك أثرًا."],
["<h2>Only if you sign in</h2>", "<h2>Seulement si tu te connectes</h2>", "<h2>Solo si inicias sesión</h2>", "<h2>Nur wenn du dich anmeldest</h2>", "<h2>Solo se accedi</h2>", "<h2>Só se você entrar</h2>", "<h2>فقط إذا سجّلت الدخول</h2>"],
["<b>Your email address</b>, to send you a one-time sign-in code. It is used for nothing else: no newsletter, no marketing.", "<b>Ton adresse e-mail</b>, pour t’envoyer un code de connexion à usage unique. Elle ne sert à rien d’autre : pas de newsletter, pas de marketing.", "<b>Tu correo</b>, para enviarte un código de acceso de un solo uso. No se usa para nada más: ni boletines ni marketing.", "<b>Deine E-Mail-Adresse</b>, um dir einen einmaligen Anmeldecode zu schicken. Sie wird für nichts anderes genutzt: kein Newsletter, kein Marketing.", "<b>Il tuo indirizzo email</b>, per inviarti un codice di accesso monouso. Non serve ad altro: niente newsletter, niente marketing.", "<b>Seu e-mail</b>, para enviar um código de acesso de uso único. Não é usado para mais nada: sem newsletter, sem marketing.", "<b>بريدك الإلكتروني</b>، لنرسل لك رمز دخول لمرة واحدة. لا يُستخدم لأي شيء آخر: لا نشرات ولا تسويق."],
["<b>Your favorites</b>, so they are there on every device.", "<b>Tes favoris</b>, pour les retrouver sur tous tes appareils.", "<b>Tus favoritos</b>, para tenerlos en todos tus dispositivos.", "<b>Deine Favoriten</b>, damit sie auf allen Geräten da sind.", "<b>I tuoi preferiti</b>, per ritrovarli su ogni dispositivo.", "<b>Seus favoritos</b>, para estarem em todos os aparelhos.", "<b>مفضلتك</b>، لتجدها على كل أجهزتك."],
["<b>One cookie</b> that keeps you signed in. Signing out removes it.", "<b>Un cookie</b> qui te garde connecté. Te déconnecter le supprime.", "<b>Una cookie</b> que mantiene tu sesión. Cerrar sesión la borra.", "<b>Ein Cookie</b>, das dich angemeldet hält. Abmelden löscht es.", "<b>Un cookie</b> che ti tiene connesso. Uscire lo cancella.", "<b>Um cookie</b> que mantém você conectado. Sair o apaga.", "<b>ملف تعريف واحد</b> يبقيك مسجّلًا. تسجيل الخروج يحذفه."],
["<h2>Good to know</h2>", "<h2>Bon à savoir</h2>", "<h2>Conviene saber</h2>", "<h2>Gut zu wissen</h2>", "<h2>Da sapere</h2>", "<h2>Bom saber</h2>", "<h2>من المفيد معرفته</h2>"],
["Sign-in codes are sent by email through Resend, and nothing else is shared with them.", "Les codes de connexion sont envoyés par e-mail via Resend, et rien d’autre ne leur est transmis.", "Los códigos se envían por correo a través de Resend, y no se les comparte nada más.", "Anmeldecodes werden per E-Mail über Resend verschickt, sonst wird nichts mit ihnen geteilt.", "I codici di accesso sono inviati via email tramite Resend, e nient’altro viene condiviso con loro.", "Os códigos são enviados por e-mail pelo Resend, e nada mais é compartilhado com eles.", "تُرسل رموز الدخول بالبريد عبر Resend، ولا يُشارك معهم أي شيء آخر."],
["Pictures are fetched by our server, so the sites they come from never see your visit.", "Les images passent par notre serveur : les sites d’où elles viennent ne voient jamais ta visite.", "Las imágenes pasan por nuestro servidor, así que los sitios de origen nunca ven tu visita.", "Bilder holt unser Server, die Herkunftsseiten sehen deinen Besuch also nie.", "Le immagini passano dal nostro server, quindi i siti d’origine non vedono mai la tua visita.", "As imagens passam pelo nosso servidor, então os sites de origem nunca veem sua visita.", "تمرّ الصور عبر خادمنا، فلا ترى المواقع الأصلية زيارتك أبدًا."],
["Your browser may keep a few settings on your device (for example the last tab you opened). They never leave it.", "Ton navigateur peut garder quelques réglages sur ton appareil (par exemple le dernier onglet ouvert). Ils n’en sortent jamais.", "Tu navegador puede guardar algunos ajustes en tu dispositivo (por ejemplo la última pestaña abierta). Nunca salen de él.", "Dein Browser kann ein paar Einstellungen auf deinem Gerät speichern (zum Beispiel den zuletzt geöffneten Tab). Sie verlassen es nie.", "Il browser può tenere alcune impostazioni sul tuo dispositivo (per esempio l’ultima scheda aperta). Non lo lasciano mai.", "Seu navegador pode guardar alguns ajustes no aparelho (por exemplo a última aba aberta). Eles nunca saem dele.", "قد يحتفظ متصفحك ببعض الإعدادات على جهازك (مثل آخر تبويب فتحته). لا تغادره أبدًا."],
["<h2>Delete everything</h2>", "<h2>Tout effacer</h2>", "<h2>Borrarlo todo</h2>", "<h2>Alles löschen</h2>", "<h2>Cancellare tutto</h2>", "<h2>Apagar tudo</h2>", "<h2>احذف كل شيء</h2>"],
["Ask the owner and your email and favorites are removed for good.", "Demande au propriétaire et ton e-mail et tes favoris sont supprimés pour de bon.", "Pídeselo al dueño y tu correo y tus favoritos se borran para siempre.", "Frag den Betreiber, und deine E-Mail und Favoriten werden endgültig gelöscht.", "Chiedi al proprietario e la tua email e i preferiti vengono cancellati per sempre.", "Peça ao dono e seu e-mail e favoritos são apagados de vez.", "اطلب من المالك وسيُحذف بريدك ومفضلتك نهائيًا."],

# ---- contact ----
["<title>Contact · Nahoko</title>", "<title>Contact · Nahoko</title>", "<title>Contacto · Nahoko</title>", "<title>Kontakt · Nahoko</title>", "<title>Contatti · Nahoko</title>", "<title>Contato · Nahoko</title>", "<title>اتصل بنا · Nahoko</title>"],
["<h1>Contact</h1>", "<h1>Contact</h1>", "<h1>Contacto</h1>", "<h1>Kontakt</h1>", "<h1>Contatti</h1>", "<h1>Contato</h1>", "<h1>اتصل بنا</h1>"],
["A question, an idea, something that does not work? Write here: the owner reads every message.", "Une question, une idée, quelque chose qui ne marche pas ? Écris ici : le propriétaire lit chaque message.", "¿Una pregunta, una idea, algo que no funciona? Escribe aquí: el dueño lee cada mensaje.", "Eine Frage, eine Idee, etwas funktioniert nicht? Schreib hier: Der Betreiber liest jede Nachricht.", "Una domanda, un’idea, qualcosa che non funziona? Scrivi qui: il proprietario legge ogni messaggio.", "Uma pergunta, uma ideia, algo que não funciona? Escreva aqui: o dono lê cada mensagem.", "سؤال، فكرة، شيء لا يعمل؟ اكتب هنا: المالك يقرأ كل رسالة."],
["Your name <span class=\"opt\">(optional)</span>", "Ton nom <span class=\"opt\">(facultatif)</span>", "Tu nombre <span class=\"opt\">(opcional)</span>", "Dein Name <span class=\"opt\">(optional)</span>", "Il tuo nome <span class=\"opt\">(facoltativo)</span>", "Seu nome <span class=\"opt\">(opcional)</span>", "اسمك <span class=\"opt\">(اختياري)</span>"],
["Your email <span class=\"opt\">(optional, only if you want an answer)</span>", "Ton e-mail <span class=\"opt\">(facultatif, seulement si tu veux une réponse)</span>", "Tu correo <span class=\"opt\">(opcional, solo si quieres respuesta)</span>", "Deine E-Mail <span class=\"opt\">(optional, nur wenn du eine Antwort willst)</span>", "La tua email <span class=\"opt\">(facoltativa, solo se vuoi una risposta)</span>", "Seu e-mail <span class=\"opt\">(opcional, só se quiser resposta)</span>", "بريدك <span class=\"opt\">(اختياري، فقط إن أردت ردًا)</span>"],
["<label>Message<textarea", "<label>Message<textarea", "<label>Mensaje<textarea", "<label>Nachricht<textarea", "<label>Messaggio<textarea", "<label>Mensagem<textarea", "<label>الرسالة<textarea"],
["<button type=\"submit\">Send</button>", "<button type=\"submit\">Envoyer</button>", "<button type=\"submit\">Enviar</button>", "<button type=\"submit\">Senden</button>", "<button type=\"submit\">Invia</button>", "<button type=\"submit\">Enviar</button>", "<button type=\"submit\">إرسال</button>"],
["b.textContent = \"Send\";", "b.textContent = \"Envoyer\";", "b.textContent = \"Enviar\";", "b.textContent = \"Senden\";", "b.textContent = \"Invia\";", "b.textContent = \"Enviar\";", "b.textContent = \"إرسال\";"],
["Your message is kept only so the owner can read it, and deleted once answered. See ", "Ton message est gardé seulement pour que le propriétaire le lise, puis supprimé une fois traité. Voir ", "Tu mensaje se guarda solo para que el dueño lo lea, y se borra una vez respondido. Ver ", "Deine Nachricht wird nur aufbewahrt, damit der Betreiber sie lesen kann, und nach der Antwort gelöscht. Siehe ", "Il tuo messaggio è conservato solo perché il proprietario lo legga, e cancellato dopo la risposta. Vedi ", "Sua mensagem é guardada só para o dono ler, e apagada depois da resposta. Veja ", "تُحفظ رسالتك فقط ليقرأها المالك، وتُحذف بعد الرد. راجع "],
["\"Write a few words first.\"", "\"Écris d’abord quelques mots.\"", "\"Escribe unas palabras primero.\"", "\"Schreib zuerst ein paar Worte.\"", "\"Scrivi prima qualche parola.\"", "\"Escreva algumas palavras primeiro.\"", "\"اكتب بضع كلمات أولًا.\""],
["\"Sending…\"", "\"Envoi…\"", "\"Enviando…\"", "\"Wird gesendet…\"", "\"Invio…\"", "\"Enviando…\"", "\"جارٍ الإرسال…\""],
["\"Could not send. Try again in a moment.\"", "\"Envoi impossible. Réessaie dans un instant.\"", "\"No se pudo enviar. Inténtalo en un momento.\"", "\"Senden fehlgeschlagen. Versuch es gleich nochmal.\"", "\"Invio non riuscito. Riprova tra poco.\"", "\"Não foi possível enviar. Tente daqui a pouco.\"", "\"تعذّر الإرسال. حاول بعد قليل.\""],
["\"Thank you! Your message was sent.\"", "\"Merci ! Ton message a été envoyé.\"", "\"¡Gracias! Tu mensaje se envió.\"", "\"Danke! Deine Nachricht wurde gesendet.\"", "\"Grazie! Il tuo messaggio è stato inviato.\"", "\"Obrigado! Sua mensagem foi enviada.\"", "\"شكرًا! أُرسلت رسالتك.\""],

# ---- how it works ----
["<title>Who we are and how it works · Nahoko</title>", "<title>Qui sommes-nous et comment ça marche · Nahoko</title>", "<title>Quiénes somos y cómo funciona · Nahoko</title>", "<title>Wer wir sind und wie es funktioniert · Nahoko</title>", "<title>Chi siamo e come funziona · Nahoko</title>", "<title>Quem somos e como funciona · Nahoko</title>", "<title>من نحن وكيف يعمل · Nahoko</title>"],
["<h1>Who we are and how it works</h1>", "<h1>Qui sommes-nous et comment ça marche</h1>", "<h1>Quiénes somos y cómo funciona</h1>", "<h1>Wer wir sind und wie es funktioniert</h1>", "<h1>Chi siamo e come funziona</h1>", "<h1>Quem somos e como funciona</h1>", "<h1>من نحن وكيف يعمل</h1>"],
["Who is behind Nahoko, where its information comes from, how titles are chosen and updated, and what the ratings mean.", "Qui est derrière Nahoko, d’où viennent ses informations, comment les titres sont choisis et mis à jour, et ce que veulent dire les notes.", "Quién está detrás de Nahoko, de dónde viene su información, cómo se eligen y actualizan los títulos y qué significan las notas.", "Wer hinter Nahoko steht, woher die Informationen kommen, wie Titel ausgewählt und aktualisiert werden und was die Bewertungen bedeuten.", "Chi c’è dietro Nahoko, da dove vengono le informazioni, come si scelgono e aggiornano i titoli e cosa significano i voti.", "Quem está por trás do Nahoko, de onde vêm as informações, como os títulos são escolhidos e atualizados e o que as notas significam.", "من يقف وراء Nahoko، ومن أين تأتي معلوماته، وكيف تُختار العناوين وتُحدّث، وماذا تعني التقييمات."],
["Nahoko is a free guide to films, series, anime and games: what is worth watching or playing, who made it, and what people think of it.", "Nahoko est un guide gratuit des films, séries, anime et jeux : ce qui vaut la peine d’être vu ou joué, qui l’a fait, et ce que les gens en pensent.", "Nahoko es una guía gratuita de películas, series, anime y juegos: qué vale la pena ver o jugar, quién lo hizo y qué opina la gente.", "Nahoko ist ein kostenloser Führer zu Filmen, Serien, Anime und Spielen: was sich lohnt, wer es gemacht hat und was die Leute davon halten.", "Nahoko è una guida gratuita a film, serie, anime e giochi: cosa vale la pena vedere o giocare, chi l’ha fatto e cosa ne pensa la gente.", "O Nahoko é um guia gratuito de filmes, séries, anime e jogos: o que vale a pena ver ou jogar, quem fez e o que as pessoas acham.", "Nahoko دليل مجاني للأفلام والمسلسلات والأنمي والألعاب: ما يستحق المشاهدة أو اللعب، ومن صنعه، ورأي الناس فيه."],
[">Who we are<", ">Qui sommes-nous<", ">Quiénes somos<", ">Wer wir sind<", ">Chi siamo<", ">Quem somos<", ">من نحن<"],
[">Sources<", ">Sources<", ">Fuentes<", ">Quellen<", ">Fonti<", ">Fontes<", ">المصادر<"],
[">Updates<", ">Mises à jour<", ">Actualizaciones<", ">Aktualisierung<", ">Aggiornamenti<", ">Atualizações<", ">التحديثات<"],
[">Which titles<", ">Quels titres<", ">Qué títulos<", ">Welche Titel<", ">Quali titoli<", ">Quais títulos<", ">أي العناوين<"],
[">Ratings<", ">Notes<", ">Notas<", ">Bewertungen<", ">Voti<", ">Notas<", ">التقييمات<"],
[">People pages<", ">Pages des personnes<", ">Páginas de personas<", ">Personenseiten<", ">Pagine delle persone<", ">Páginas de pessoas<", ">صفحات الأشخاص<"],
[">Automatic texts<", ">Textes automatiques<", ">Textos automáticos<", ">Automatische Texte<", ">Testi automatici<", ">Textos automáticos<", ">نصوص تلقائية<"],
[">Independence<", ">Indépendance<", ">Independencia<", ">Unabhängigkeit<", ">Indipendenza<", ">Independência<", ">الاستقلالية<"],
[">Limits<", ">Limites<", ">Límites<", ">Grenzen<", ">Limiti<", ">Limites<", ">الحدود<"],
[">Report an error<", ">Signaler une erreur<", ">Avisar de un error<", ">Fehler melden<", ">Segnala un errore<", ">Informar um erro<", ">الإبلاغ عن خطأ<"],
["<h2 id=\"who\">Who is behind Nahoko</h2>", "<h2 id=\"who\">Qui est derrière Nahoko</h2>", "<h2 id=\"who\">Quién está detrás de Nahoko</h2>", "<h2 id=\"who\">Wer hinter Nahoko steht</h2>", "<h2 id=\"who\">Chi c’è dietro Nahoko</h2>", "<h2 id=\"who\">Quem está por trás do Nahoko</h2>", "<h2 id=\"who\">من يقف وراء Nahoko</h2>"],
["One developer, as a passion project. Nahoko runs on a small personal server. There is no company and no investor behind it, and it has no link with IMDb, TMDB, TVmaze, Wikipedia, YouTube or any streaming service.", "Un seul développeur, par passion. Nahoko tourne sur un petit serveur personnel. Il n’y a ni entreprise ni investisseur derrière, et aucun lien avec IMDb, TMDB, TVmaze, Wikipédia, YouTube ou un service de streaming.", "Un solo desarrollador, por pasión. Nahoko funciona en un pequeño servidor personal. No hay empresa ni inversores detrás, y no tiene relación con IMDb, TMDB, TVmaze, Wikipedia, YouTube ni ningún servicio de streaming.", "Ein einzelner Entwickler, aus Leidenschaft. Nahoko läuft auf einem kleinen privaten Server. Keine Firma, keine Investoren, und keine Verbindung zu IMDb, TMDB, TVmaze, Wikipedia, YouTube oder einem Streamingdienst.", "Un solo sviluppatore, per passione. Nahoko gira su un piccolo server personale. Non ci sono aziende né investitori dietro, e nessun legame con IMDb, TMDB, TVmaze, Wikipedia, YouTube o servizi di streaming.", "Um único desenvolvedor, por paixão. O Nahoko roda num pequeno servidor pessoal. Não há empresa nem investidores, e nenhuma ligação com IMDb, TMDB, TVmaze, Wikipédia, YouTube ou serviços de streaming.", "مطوّر واحد، بدافع الشغف. يعمل Nahoko على خادم شخصي صغير. لا شركة ولا مستثمرون وراءه، ولا علاقة له بـ IMDb أو TMDB أو TVmaze أو ويكيبيديا أو يوتيوب أو أي خدمة بث."],
["<h2 id=\"sources\">Where the information comes from</h2>", "<h2 id=\"sources\">D’où viennent les informations</h2>", "<h2 id=\"sources\">De dónde viene la información</h2>", "<h2 id=\"sources\">Woher die Informationen kommen</h2>", "<h2 id=\"sources\">Da dove vengono le informazioni</h2>", "<h2 id=\"sources\">De onde vêm as informações</h2>", "<h2 id=\"sources\">من أين تأتي المعلومات</h2>"],
["(its free daily datasets): titles, years, genres, running times, ratings and vote counts, cast and crew, and the list of episodes of every series.", "(ses jeux de données quotidiens gratuits) : titres, années, genres, durées, notes et nombre de votes, distribution et équipe, et la liste des épisodes de chaque série.", "(sus datos diarios gratuitos): títulos, años, géneros, duraciones, notas y votos, reparto y equipo, y la lista de episodios de cada serie.", "(seine kostenlosen täglichen Datensätze): Titel, Jahre, Genres, Laufzeiten, Bewertungen und Stimmen, Besetzung und Stab sowie die Folgenliste jeder Serie.", "(i suoi dataset quotidiani gratuiti): titoli, anni, generi, durate, voti e numero di voti, cast e troupe, e l’elenco degli episodi di ogni serie.", "(seus dados diários gratuitos): títulos, anos, gêneros, durações, notas e votos, elenco e equipe, e a lista de episódios de cada série.", "(بياناته اليومية المجانية): العناوين والسنوات والأنواع والمدد والتقييمات وعدد الأصوات وطاقم العمل وقائمة حلقات كل مسلسل."],
[": posters, plot summaries and portraits. This product uses the TMDB API but is not endorsed or certified by TMDB.", " : affiches, résumés et portraits. Ce produit utilise l’API TMDB mais n’est ni approuvé ni certifié par TMDB.", ": pósteres, sinopsis y retratos. Este producto usa la API de TMDB pero no está avalado ni certificado por TMDB.", ": Poster, Inhaltsangaben und Porträts. Dieses Produkt nutzt die TMDB-API, ist aber nicht von TMDB unterstützt oder zertifiziert.", ": locandine, trame e ritratti. Questo prodotto usa l’API di TMDB ma non è approvato né certificato da TMDB.", ": pôsteres, sinopses e retratos. Este produto usa a API do TMDB, mas não é endossado nem certificado pelo TMDB.", ": الملصقات والملخصات والصور الشخصية. يستخدم هذا المنتج واجهة TMDB لكنه غير معتمد منها."],
[": wide pictures for series, air dates of episodes, and some cast portraits.", " : grandes images des séries, dates de diffusion des épisodes et quelques portraits.", ": imágenes anchas de series, fechas de emisión de episodios y algunos retratos.", ": breite Bilder für Serien, Ausstrahlungsdaten der Folgen und einige Porträts.", ": immagini larghe delle serie, date di messa in onda e alcuni ritratti.", ": imagens largas das séries, datas de exibição e alguns retratos.", ": صور عريضة للمسلسلات، ومواعيد عرض الحلقات، وبعض صور الممثلين."],
[": which series and films are anime.", " : quelles séries et quels films sont des anime.", ": qué series y películas son anime.", ": welche Serien und Filme Anime sind.", ": quali serie e film sono anime.", ": quais séries e filmes são anime.", ": أي المسلسلات والأفلام أنمي."],
["<b>Wikidata and Wikipedia</b>: games, the countries of films, and facts about people (birth, death, short biography). Wikipedia texts are under the CC BY-SA licence and each one links to its article.", "<b>Wikidata et Wikipédia</b> : les jeux, les pays des films et des faits sur les personnes (naissance, décès, courte biographie). Les textes de Wikipédia sont sous licence CC BY-SA et chacun renvoie à son article.", "<b>Wikidata y Wikipedia</b>: juegos, países de las películas y datos de personas (nacimiento, muerte, breve biografía). Los textos de Wikipedia están bajo licencia CC BY-SA y cada uno enlaza a su artículo.", "<b>Wikidata und Wikipedia</b>: Spiele, die Länder der Filme und Fakten über Personen (Geburt, Tod, kurze Biografie). Wikipedia-Texte stehen unter CC BY-SA und verlinken jeweils ihren Artikel.", "<b>Wikidata e Wikipedia</b>: giochi, paesi dei film e dati sulle persone (nascita, morte, breve biografia). I testi di Wikipedia sono sotto licenza CC BY-SA e ognuno rimanda al suo articolo.", "<b>Wikidata e Wikipédia</b>: jogos, países dos filmes e dados sobre pessoas (nascimento, morte, breve biografia). Os textos da Wikipédia estão sob a licença CC BY-SA e cada um leva ao seu artigo.", "<b>ويكي بيانات وويكيبيديا</b>: الألعاب، وبلدان الأفلام، ومعلومات عن الأشخاص (الميلاد، الوفاة، سيرة قصيرة). نصوص ويكيبيديا بترخيص CC BY-SA وكل نص يربط بمقالته."],
["<b>YouTube</b>: trailers, and a still from the trailer as the wide picture on film pages.", "<b>YouTube</b> : les bandes-annonces, et une image de la bande-annonce comme grande image des pages de films.", "<b>YouTube</b>: tráileres, y un fotograma del tráiler como imagen ancha de las películas.", "<b>YouTube</b>: Trailer und ein Standbild daraus als breites Bild auf Filmseiten.", "<b>YouTube</b>: trailer, e un fotogramma del trailer come immagine larga delle pagine dei film.", "<b>YouTube</b>: trailers, e um quadro do trailer como imagem larga das páginas de filmes.", "<b>يوتيوب</b>: الإعلانات، ولقطة منها كصورة عريضة في صفحات الأفلام."],
["<b>News</b>: headlines and short summaries from the publishers’ own public feeds, always credited to them. We never copy whole articles.", "<b>Actualités</b> : titres et courts résumés tirés des flux publics des éditeurs, toujours crédités. Nous ne copions jamais d’articles entiers.", "<b>Noticias</b>: titulares y breves resúmenes de los canales públicos de los medios, siempre citados. Nunca copiamos artículos enteros.", "<b>News</b>: Schlagzeilen und kurze Zusammenfassungen aus den öffentlichen Feeds der Verlage, immer mit Quelle. Wir kopieren nie ganze Artikel.", "<b>Notizie</b>: titoli e brevi riassunti dai feed pubblici degli editori, sempre citati. Non copiamo mai articoli interi.", "<b>Notícias</b>: manchetes e resumos curtos dos feeds públicos dos veículos, sempre creditados. Nunca copiamos artigos inteiros.", "<b>الأخبار</b>: عناوين وملخصات قصيرة من خلاصات الناشرين العامة، مع ذكر المصدر دائمًا. لا ننسخ مقالات كاملة أبدًا."],
["<h2 id=\"updates\">How it is kept up to date</h2>", "<h2 id=\"updates\">Comment c’est mis à jour</h2>", "<h2 id=\"updates\">Cómo se mantiene al día</h2>", "<h2 id=\"updates\">Wie es aktuell bleibt</h2>", "<h2 id=\"updates\">Come resta aggiornato</h2>", "<h2 id=\"updates\">Como é atualizado</h2>", "<h2 id=\"updates\">كيف يبقى محدّثًا</h2>"],
["The catalogue is rebuilt every week from IMDb’s datasets, quietly in the background: the old one stays online until the new one is ready. Posters and pictures are fetched the first time someone needs them, then kept. News is checked every 30 minutes. Facts about people are refreshed every month.", "Le catalogue est reconstruit chaque semaine à partir des données IMDb, discrètement : l’ancien reste en ligne jusqu’à ce que le nouveau soit prêt. Affiches et images sont récupérées la première fois qu’on en a besoin, puis gardées. Les actualités sont vérifiées toutes les 30 minutes. Les infos sur les personnes sont rafraîchies chaque mois.", "El catálogo se reconstruye cada semana con los datos de IMDb, en segundo plano: el anterior sigue en línea hasta que el nuevo está listo. Pósteres e imágenes se obtienen la primera vez que se necesitan y se guardan. Las noticias se revisan cada 30 minutos. Los datos de personas se renuevan cada mes.", "Der Katalog wird jede Woche aus den IMDb-Daten neu gebaut, leise im Hintergrund: Der alte bleibt online, bis der neue fertig ist. Poster und Bilder werden beim ersten Bedarf geholt und behalten. News werden alle 30 Minuten geprüft. Personendaten werden monatlich erneuert.", "Il catalogo viene ricostruito ogni settimana dai dati IMDb, in silenzio: il vecchio resta online finché il nuovo non è pronto. Locandine e immagini si scaricano la prima volta che servono, poi si conservano. Le notizie si controllano ogni 30 minuti. I dati sulle persone si aggiornano ogni mese.", "O catálogo é reconstruído toda semana a partir dos dados do IMDb, em segundo plano: o antigo fica no ar até o novo estar pronto. Pôsteres e imagens são buscados na primeira vez que alguém precisa e guardados. As notícias são verificadas a cada 30 minutos. Os dados de pessoas são renovados todo mês.", "يُعاد بناء الكتالوج كل أسبوع من بيانات IMDb بهدوء في الخلفية: يبقى القديم متاحًا حتى يجهز الجديد. تُجلب الملصقات والصور أول مرة يحتاجها أحد ثم تُحفظ. تُفحص الأخبار كل 30 دقيقة. وتُحدّث معلومات الأشخاص كل شهر."],
["<h2 id=\"choice\">Which titles are in the catalogue</h2>", "<h2 id=\"choice\">Quels titres sont dans le catalogue</h2>", "<h2 id=\"choice\">Qué títulos hay en el catálogo</h2>", "<h2 id=\"choice\">Welche Titel im Katalog sind</h2>", "<h2 id=\"choice\">Quali titoli sono nel catalogo</h2>", "<h2 id=\"choice\">Quais títulos estão no catálogo</h2>", "<h2 id=\"choice\">أي العناوين في الكتالوج</h2>"],
["Titles that many people have seen and rated: films with tens of thousands of votes on IMDb, series with a little fewer. Then, for each country, its best-known national films and series, so that great titles from Egypt, Korea, Italy or India are not drowned out by Hollywood. Plus the 5,000 best-known anime and thousands of games for PC, PlayStation, Xbox and Switch. <b>No one can pay to be listed or to be shown first.</b>", "Les titres que beaucoup de gens ont vus et notés : des films avec des dizaines de milliers de votes sur IMDb, des séries avec un peu moins. Puis, pour chaque pays, ses films et séries les plus connus, pour que les grands titres d’Égypte, de Corée, d’Italie ou d’Inde ne soient pas noyés par Hollywood. Plus les 5 000 anime les plus connus et des milliers de jeux PC, PlayStation, Xbox et Switch. <b>Personne ne peut payer pour être listé ou mis en avant.</b>", "Títulos que mucha gente ha visto y valorado: películas con decenas de miles de votos en IMDb, series con algo menos. Luego, para cada país, sus películas y series más conocidas, para que los grandes títulos de Egipto, Corea, Italia o India no queden ahogados por Hollywood. Además, los 5.000 anime más conocidos y miles de juegos de PC, PlayStation, Xbox y Switch. <b>Nadie puede pagar para aparecer ni para salir primero.</b>", "Titel, die viele gesehen und bewertet haben: Filme mit Zehntausenden Stimmen auf IMDb, Serien mit etwas weniger. Dann für jedes Land seine bekanntesten Filme und Serien, damit großartige Titel aus Ägypten, Korea, Italien oder Indien nicht von Hollywood überdeckt werden. Dazu die 5.000 bekanntesten Anime und Tausende Spiele für PC, PlayStation, Xbox und Switch. <b>Niemand kann zahlen, um gelistet oder vorne gezeigt zu werden.</b>", "Titoli che molte persone hanno visto e votato: film con decine di migliaia di voti su IMDb, serie con un po’ meno. Poi, per ogni paese, i suoi film e serie più noti, perché i grandi titoli di Egitto, Corea, Italia o India non siano sommersi da Hollywood. In più i 5.000 anime più noti e migliaia di giochi per PC, PlayStation, Xbox e Switch. <b>Nessuno può pagare per essere elencato o mostrato per primo.</b>", "Títulos que muita gente viu e avaliou: filmes com dezenas de milhares de votos no IMDb, séries com um pouco menos. Depois, para cada país, seus filmes e séries mais conhecidos, para que grandes títulos do Egito, Coreia, Itália ou Índia não sejam abafados por Hollywood. Mais os 5.000 anime mais conhecidos e milhares de jogos de PC, PlayStation, Xbox e Switch. <b>Ninguém pode pagar para aparecer ou ser mostrado primeiro.</b>", "عناوين شاهدها وقيّمها كثيرون: أفلام بعشرات آلاف الأصوات على IMDb، ومسلسلات بأقل قليلًا. ثم لكل بلد أشهر أفلامه ومسلسلاته، كي لا تغرق الأعمال الكبيرة من مصر وكوريا وإيطاليا والهند وسط هوليوود. إضافة إلى أشهر 5,000 أنمي وآلاف الألعاب للحاسوب وبلايستيشن وإكس بوكس وسويتش. <b>لا أحد يستطيع الدفع ليُدرج أو يظهر أولًا.</b>"],
["<h2 id=\"ratings\">What the ratings mean</h2>", "<h2 id=\"ratings\">Ce que veulent dire les notes</h2>", "<h2 id=\"ratings\">Qué significan las notas</h2>", "<h2 id=\"ratings\">Was die Bewertungen bedeuten</h2>", "<h2 id=\"ratings\">Cosa significano i voti</h2>", "<h2 id=\"ratings\">O que as notas significam</h2>", "<h2 id=\"ratings\">ماذا تعني التقييمات</h2>"],
["<b>Films and series</b>: the IMDb user rating, out of 10, with the number of votes.", "<b>Films et séries</b> : la note des utilisateurs IMDb, sur 10, avec le nombre de votes.", "<b>Películas y series</b>: la nota de los usuarios de IMDb, sobre 10, con el número de votos.", "<b>Filme und Serien</b>: die IMDb-Nutzerwertung von 10, mit der Zahl der Stimmen.", "<b>Film e serie</b>: il voto degli utenti IMDb, su 10, con il numero di voti.", "<b>Filmes e séries</b>: a nota dos usuários do IMDb, de 0 a 10, com o número de votos.", "<b>الأفلام والمسلسلات</b>: تقييم مستخدمي IMDb من 10، مع عدد الأصوات."],
["<b>“Top rated” shelves</b>: sorted by a score that also weighs the number of votes, so a 9.1 from 2,000 votes does not beat <i>12 Angry Men</i>.", "<b>Rayons « Les mieux notés »</b> : triés par un score qui tient aussi compte du nombre de votes, pour qu’un 9,1 avec 2 000 votes ne batte pas <i>12 Hommes en colère</i>.", "<b>Estantes «Mejor valorados»</b>: ordenados por una puntuación que también pesa los votos, para que un 9,1 con 2.000 votos no gane a <i>12 hombres sin piedad</i>.", "<b>Regale „Bestbewertet“</b>: sortiert nach einem Wert, der auch die Stimmenzahl gewichtet, damit eine 9,1 aus 2.000 Stimmen nicht <i>Die zwölf Geschworenen</i> schlägt.", "<b>Scaffali «I più votati»</b>: ordinati con un punteggio che pesa anche il numero di voti, così un 9,1 con 2.000 voti non batte <i>La parola ai giurati</i>.", "<b>Prateleiras “Mais bem avaliados”</b>: ordenadas por uma pontuação que também pesa os votos, para que um 9,1 com 2.000 votos não vença <i>12 Homens e uma Sentença</i>.", "<b>رفوف «الأعلى تقييمًا»</b>: مرتبة بنتيجة تأخذ عدد الأصوات في الحسبان، كي لا يتفوق 9.1 من 2,000 صوت على <i>12 رجلًا غاضبًا</i>."],
["<b>Episodes</b>: each episode’s IMDb rating, shown as a coloured chart per season (or per block of 25 episodes for very long seasons).", "<b>Épisodes</b> : la note IMDb de chaque épisode, en tableau coloré par saison (ou par bloc de 25 épisodes pour les très longues saisons).", "<b>Episodios</b>: la nota IMDb de cada episodio, en un gráfico de colores por temporada (o por bloques de 25 episodios en temporadas muy largas).", "<b>Folgen</b>: die IMDb-Wertung jeder Folge als farbige Tabelle pro Staffel (oder pro Block von 25 Folgen bei sehr langen Staffeln).", "<b>Episodi</b>: il voto IMDb di ogni episodio, in un grafico colorato per stagione (o per blocchi di 25 episodi nelle stagioni molto lunghe).", "<b>Episódios</b>: a nota IMDb de cada episódio, num gráfico colorido por temporada (ou por blocos de 25 episódios nas temporadas muito longas).", "<b>الحلقات</b>: تقييم IMDb لكل حلقة، في مخطط ملوّن لكل موسم (أو لكل 25 حلقة في المواسم الطويلة جدًا)."],
["<b>Games</b>: the critics’ score (Metacritic) when Wikidata has it.", "<b>Jeux</b> : la note de la critique (Metacritic) quand Wikidata l’a.", "<b>Juegos</b>: la nota de la crítica (Metacritic) cuando Wikidata la tiene.", "<b>Spiele</b>: die Kritikerwertung (Metacritic), wenn Wikidata sie hat.", "<b>Giochi</b>: il voto della critica (Metacritic) quando Wikidata ce l’ha.", "<b>Jogos</b>: a nota da crítica (Metacritic) quando a Wikidata a tem.", "<b>الألعاب</b>: تقييم النقاد (Metacritic) عندما يتوفر في ويكي بيانات."],
["<h2 id=\"people\">People pages</h2>", "<h2 id=\"people\">Pages des personnes</h2>", "<h2 id=\"people\">Páginas de personas</h2>", "<h2 id=\"people\">Personenseiten</h2>", "<h2 id=\"people\">Pagine delle persone</h2>", "<h2 id=\"people\">Páginas de pessoas</h2>", "<h2 id=\"people\">صفحات الأشخاص</h2>"],
["Every actor, director and writer of a catalogue title has a page: their portrait, date and place of birth, a short biography from Wikipedia, their best-known titles and everything they made that is in the catalogue. The filmography is limited to the catalogue, so it is not always complete.", "Chaque acteur, réalisateur et scénariste d’un titre du catalogue a sa page : portrait, date et lieu de naissance, courte biographie de Wikipédia, titres les plus connus et tout ce qu’il a fait qui est dans le catalogue. La filmographie se limite au catalogue, elle n’est donc pas toujours complète.", "Cada actor, director y guionista de un título del catálogo tiene su página: retrato, fecha y lugar de nacimiento, una breve biografía de Wikipedia, sus títulos más conocidos y todo lo que hizo que está en el catálogo. La filmografía se limita al catálogo, así que no siempre está completa.", "Jeder Schauspieler, Regisseur und Autor eines Katalogtitels hat eine Seite: Porträt, Geburtsdatum und -ort, eine kurze Wikipedia-Biografie, die bekanntesten Titel und alles, was im Katalog ist. Die Filmografie ist auf den Katalog beschränkt und daher nicht immer vollständig.", "Ogni attore, regista e sceneggiatore di un titolo del catalogo ha una pagina: ritratto, data e luogo di nascita, una breve biografia da Wikipedia, i titoli più noti e tutto ciò che ha fatto ed è nel catalogo. La filmografia è limitata al catalogo, quindi non sempre è completa.", "Cada ator, diretor e roteirista de um título do catálogo tem uma página: retrato, data e local de nascimento, uma breve biografia da Wikipédia, os títulos mais conhecidos e tudo o que fez que está no catálogo. A filmografia se limita ao catálogo, então nem sempre é completa.", "لكل ممثل ومخرج وكاتب في عناوين الكتالوج صفحة: صورته، وتاريخ ومكان ميلاده، وسيرة قصيرة من ويكيبيديا، وأشهر أعماله، وكل ما صنعه وهو في الكتالوج. الأعمال محدودة بالكتالوج، فقد لا تكون كاملة."],
["<h2 id=\"texts\">Automatic texts</h2>", "<h2 id=\"texts\">Textes automatiques</h2>", "<h2 id=\"texts\">Textos automáticos</h2>", "<h2 id=\"texts\">Automatische Texte</h2>", "<h2 id=\"texts\">Testi automatici</h2>", "<h2 id=\"texts\">Textos automáticos</h2>", "<h2 id=\"texts\">نصوص تلقائية</h2>"],
["Some short texts are written automatically from our own data, for example the “Background” notes under a news story (year, rating, cast of the titles it mentions). They are facts from the catalogue, not opinions. Plot summaries come from TMDB.", "Certains textes courts sont écrits automatiquement à partir de nos données, par exemple les notes « Contexte » sous une actualité (année, note, distribution des titres cités). Ce sont des faits du catalogue, pas des opinions. Les résumés viennent de TMDB.", "Algunos textos cortos se escriben automáticamente con nuestros datos, por ejemplo las notas «Contexto» bajo una noticia (año, nota, reparto de los títulos que menciona). Son datos del catálogo, no opiniones. Las sinopsis vienen de TMDB.", "Einige kurze Texte entstehen automatisch aus unseren Daten, etwa die „Hintergrund“-Notizen unter einer Meldung (Jahr, Wertung, Besetzung der genannten Titel). Es sind Fakten aus dem Katalog, keine Meinungen. Inhaltsangaben stammen von TMDB.", "Alcuni testi brevi sono scritti automaticamente dai nostri dati, per esempio le note «Contesto» sotto una notizia (anno, voto, cast dei titoli citati). Sono fatti del catalogo, non opinioni. Le trame vengono da TMDB.", "Alguns textos curtos são escritos automaticamente com nossos dados, por exemplo as notas “Contexto” sob uma notícia (ano, nota, elenco dos títulos citados). São fatos do catálogo, não opiniões. As sinopses vêm do TMDB.", "بعض النصوص القصيرة تُكتب تلقائيًا من بياناتنا، مثل ملاحظات «خلفية» تحت الخبر (السنة والتقييم وطاقم العناوين المذكورة). إنها حقائق من الكتالوج لا آراء. والملخصات من TMDB."],
["<h2 id=\"independence\">Independence</h2>", "<h2 id=\"independence\">Indépendance</h2>", "<h2 id=\"independence\">Independencia</h2>", "<h2 id=\"independence\">Unabhängigkeit</h2>", "<h2 id=\"independence\">Indipendenza</h2>", "<h2 id=\"independence\">Independência</h2>", "<h2 id=\"independence\">الاستقلالية</h2>"],
["No ads, no affiliate links, no tracking, no paid placement. Nahoko does not host or sell any film. Signing in is optional and only keeps your favorites; see the ", "Pas de pub, pas de liens affiliés, pas de pistage, pas de placement payé. Nahoko n’héberge ni ne vend aucun film. La connexion est facultative et sert seulement à garder tes favoris ; voir la ", "Sin anuncios, sin enlaces de afiliados, sin rastreo, sin posiciones pagadas. Nahoko no aloja ni vende películas. Iniciar sesión es opcional y solo guarda tus favoritos; mira la ", "Keine Werbung, keine Affiliate-Links, kein Tracking, keine bezahlten Plätze. Nahoko hostet und verkauft keine Filme. Die Anmeldung ist optional und speichert nur deine Favoriten; siehe ", "Niente pubblicità, niente link di affiliazione, niente tracciamento, niente posizioni a pagamento. Nahoko non ospita né vende film. L’accesso è facoltativo e serve solo per i preferiti; vedi la ", "Sem anúncios, sem links de afiliados, sem rastreamento, sem posições pagas. O Nahoko não hospeda nem vende filmes. Entrar é opcional e só guarda seus favoritos; veja a ", "لا إعلانات، ولا روابط تسويق، ولا تتبّع، ولا مواضع مدفوعة. لا يستضيف Nahoko أي فيلم ولا يبيعه. تسجيل الدخول اختياري ويحفظ مفضلتك فقط؛ راجع "],
[">privacy page<", ">page confidentialité<", ">página de privacidad<", ">Datenschutzseite<", ">pagina privacy<", ">página de privacidade<", ">صفحة الخصوصية<"],
["<h2 id=\"limits\">Limits</h2>", "<h2 id=\"limits\">Limites</h2>", "<h2 id=\"limits\">Límites</h2>", "<h2 id=\"limits\">Grenzen</h2>", "<h2 id=\"limits\">Limiti</h2>", "<h2 id=\"limits\">Limites</h2>", "<h2 id=\"limits\">الحدود</h2>"],
["Our sources can be wrong or incomplete, and we can only be as right as they are.", "Nos sources peuvent se tromper ou être incomplètes, et nous ne pouvons pas être plus justes qu’elles.", "Nuestras fuentes pueden equivocarse o estar incompletas, y solo podemos ser tan exactos como ellas.", "Unsere Quellen können falsch oder lückenhaft sein, und wir können nur so genau sein wie sie.", "Le nostre fonti possono sbagliare o essere incomplete, e possiamo essere precisi solo quanto loro.", "Nossas fontes podem errar ou estar incompletas, e só podemos ser tão exatos quanto elas.", "قد تخطئ مصادرنا أو تكون ناقصة، ولا يمكننا أن نكون أدق منها."],
["Some titles or people may have no picture or no description yet.", "Certains titres ou personnes n’ont peut-être pas encore d’image ou de description.", "Algunos títulos o personas pueden no tener aún imagen ni descripción.", "Manche Titel oder Personen haben vielleicht noch kein Bild oder keine Beschreibung.", "Alcuni titoli o persone potrebbero non avere ancora immagine o descrizione.", "Alguns títulos ou pessoas podem ainda não ter imagem ou descrição.", "قد لا تكون لبعض العناوين أو الأشخاص صورة أو وصف بعد."],
["Only titles in the catalogue have their own page.", "Seuls les titres du catalogue ont leur propre page.", "Solo los títulos del catálogo tienen página propia.", "Nur Titel im Katalog haben eine eigene Seite.", "Solo i titoli del catalogo hanno una pagina propria.", "Só os títulos do catálogo têm página própria.", "العناوين الموجودة في الكتالوج فقط لها صفحات خاصة."],
["<h2 id=\"errors\">How to report an error</h2>", "<h2 id=\"errors\">Comment signaler une erreur</h2>", "<h2 id=\"errors\">Cómo avisar de un error</h2>", "<h2 id=\"errors\">So meldest du einen Fehler</h2>", "<h2 id=\"errors\">Come segnalare un errore</h2>", "<h2 id=\"errors\">Como informar um erro</h2>", "<h2 id=\"errors\">كيف تبلغ عن خطأ</h2>"],
["Write to us on the ", "Écris-nous sur la ", "Escríbenos en la ", "Schreib uns über die ", "Scrivici dalla ", "Escreva para nós na ", "اكتب لنا عبر "],
[">contact page<", ">page contact<", ">página de contacto<", ">Kontaktseite<", ">pagina contatti<", ">página de contato<", ">صفحة الاتصال<"],
[": say which page and what is wrong. Errors that come from IMDb, TMDB or Wikipedia are best corrected there too, so everyone benefits.", " : dis quelle page et ce qui ne va pas. Les erreurs qui viennent d’IMDb, TMDB ou Wikipédia gagnent à y être corrigées aussi, pour que tout le monde en profite.", ": di qué página y qué está mal. Los errores que vienen de IMDb, TMDB o Wikipedia conviene corregirlos también allí, para que todos se beneficien.", ": Sag, welche Seite und was falsch ist. Fehler aus IMDb, TMDB oder Wikipedia korrigiert man am besten auch dort, damit alle profitieren.", ": indica quale pagina e cosa non va. Gli errori che vengono da IMDb, TMDB o Wikipedia conviene correggerli anche lì, così ne beneficiano tutti.", ": diga qual página e o que está errado. Erros que vêm do IMDb, TMDB ou Wikipédia é melhor corrigir lá também, para todos se beneficiarem.", ": اذكر الصفحة وما الخطأ. ويُفضّل تصحيح الأخطاء القادمة من IMDb أو TMDB أو ويكيبيديا هناك أيضًا ليستفيد الجميع."],
]

def build():
    for i, lg in enumerate(LANGS, 1):
        os.makedirs(os.path.join(HERE, lg), exist_ok=True)
        for name in ("about", "methodology", "privacy", "contact"):
            s = open(os.path.join(HERE, name + ".html"), encoding="utf-8").read()
            for row in sorted(T, key=lambda r: -len(r[0])):
                s = s.replace(row[0], row[i])
            s = s.replace('<html lang="en">', '<html lang="%s"%s>' % (lg, ' dir="rtl"' if lg == "ar" else ""), 1)
            # links stay in the language: /about -> /fr/about, / -> /fr/films
            s = re.sub(r'href="/(about|methodology|privacy|contact|news)"', lambda m: 'href="/%s/%s"' % (lg, m.group(1)) if m.group(1) != "news" else 'href="/news"', s)
            s = s.replace('href="/"', 'href="/%s/%s"' % (lg, SEC[lg]))
            s = s.replace('"item":"/"', '"item":"/%s/"' % lg).replace('"item":"/methodology"', '"item":"/%s/methodology"' % lg)
            if lg == "ar": s = s.replace("</style>", "ul{padding-left:0;padding-right:20px}</style>", 1)
            open(os.path.join(HERE, lg, name + ".html"), "w", encoding="utf-8", newline="\n").write(s)
    print("built", len(LANGS) * 4, "pages")

if __name__ == "__main__":
    build()
